name: Deploy Cosmos DB

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_cosmos_db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Cosmos DB
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./infra/database/cosmos_db_template.json
          parameters: ./infra/database/cosmos_db_parameters.json
          deploymentName: deploy-cosmos-db
